spring.application.name=A003_SpringRestAPI_FK8
spring.datasource.url=jdbc:mysql://localhost:3306/fkDB
spring.datasource.username=root
spring.datasource.password=drsn@1028
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
server.port=8088
