spring.application.name=SpringBoot
# ===============================
# Server Configuration
# ===============================
server.port=8081

# ===============================
# JSP View Resolver
# ===============================
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# ===============================
# Database Configuration
# ===============================
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/springdb
spring.datasource.username=root
spring.datasource.password=drsn@1028

# ===============================
# Hibernate / JPA Configuration
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# JSP & JSTL Support
# ===============================
spring.mvc.hiddenmethod.filter.enabled=true
